export type Phase = 'build' | 'raid' | 'victory' | 'defeat';
export type BlockType = 'wall' | 'trap' | 'turret' | 'frost';
export type RaiderKind = 'grunt' | 'runner' | 'brute';
export type RewardChoice = 'repair' | 'turret' | 'frost';
export type Cell = { x: number; z: number };
export type RaidPlan = {
  day: number;
  total: number;
  dangerLane: number;
  mix: Record<RaiderKind, number>;
  rewardPreview: Resources;
};
export type Block = { type: BlockType; hp: number; cooldown?: number };
export type Raider = {
  id: string;
  kind: RaiderKind;
  cell: Cell;
  hp: number;
  maxHp: number;
  speed: number;
  bounty: number;
  slowed?: number;
  path: Cell[];
  pathIndex: number;
  resolved?: boolean;
  attackCooldown: number;
};
export type Resources = Record<BlockType, number>;
export type RewardOption = {
  id: RewardChoice;
  title: string;
  description: string;
  resources: Partial<Resources>;
  coreRepair: number;
};
export type GameState = {
  day: number;
  phase: Phase;
  paused: boolean;
  size: number;
  core: Cell;
  coreHp: number;
  maxCoreHp: number;
  resources: Resources;
  selected: BlockType;
  blocks: Record<string, Block>;
  raiders: Raider[];
  totalRaiders: number;
  coins: number;
  kills: number;
  combo: number;
  combatLog: string[];
  dangerLane: number;
  message: string;
};
